sudo: required

language: php
php:
  - '7.1'

notifications:
  email:
    recipients:
      - karima.rafes@gmail.com
    on_success: always # default: change (other : never)
    on_failure: always # default: always

env:
  global:
    - URI="https://travis-ci.org/BorderCloud/tft-jena-fuseki/builds/$((TRAVIS_JOB_ID - 1))"
    - NAME="Jena Fuseki"
    - SOFTWARE_DESCRIBE="Jena Fuseki"
    - VERSION="4.0.0"
#    - SPARQLSCORE_DATABASE="134.158.74.247"
    - SPARQLSCORE_DATABASE="172.30.0.6:8080" #local

services:
  - docker

before_install:
# Download docker's images 
  - docker pull bordercloud/tft-virtuoso7-stable
#  - docker pull bordercloud/tft-jena-fuseki

# Compile the docker's project 
  - docker build -t tft-jena-fuseki .

script:
# Deploy TFT
  - docker system prune -f
  - docker-compose up -d 

#   - sleep 30s
  
#   - git clone --recursive https://github.com/BorderCloud/TFT.git
#   - cd TFT
# # install SPARQL client 
#   - composer install
# # install JMeter 
#   - wget http://mirrors.standaloneinstaller.com/apache//jmeter/binaries/apache-jmeter-5.4.1.tgz
#   - tar xvzf apache-jmeter-5.4.1.tgz
#   - mv  apache-jmeter-5.4.1 jmeter
#   - rm apache-jmeter-5.4.1.tgz
  
#   -   php ./tft-testsuite -a -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update
#   -   php ./tft -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -tt fuseki -te http://172.17.0.2/sparql -r ${URI} -o ./junit --softwareName="${NAME}"  --softwareDescribeTag=${VERSION}  --softwareDescribe="${TRAVIS_COMMIT}" 
#   -   php ./tft-score -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -r  ${URI}

#   -   docker-compose stop
  
# Save the Docker image
after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#     docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
#     docker push bordercloud/tft-jena-fuseki;
#     fi
