version: "3"
services:
  tft-jena-fuseki:
    image: tft-jena-fuseki:latest
    hostname: tft-jena-fuseki
    container_name: instance.tft-jena-fuseki
    privileged: true
    networks:
      tft:
        ipv4_address:  172.18.0.2
    extra_hosts:
        - "example.org:172.18.0.3"
        - "example1.org:172.18.0.4"
        - "example2.org:172.18.0.5"
        
  tft-example:
    image: tft-jena-fuseki:latest
    hostname: example.org
    container_name: instance.tft.example.org
    privileged: true
    networks:
      tft:
        ipv4_address: 172.18.0.3
    extra_hosts:
        - "example1.org:172.18.0.4"
        - "example2.org:172.18.0.5"
        
  tft-example1:
    image: tft-jena-fuseki:latest
    hostname: example1.org
    container_name: instance.tft.example1.org
    privileged: true
    networks:
      tft:
        ipv4_address: 172.18.0.4
    extra_hosts:
        - "example.org:172.18.0.3"
        - "example2.org:172.18.0.5"
        
  tft-example2:
    image: tft-jena-fuseki:latest
    hostname: example2.org
    container_name: instance.tft.example2.org
    privileged: true
    networks:
      tft:
        ipv4_address: 172.18.0.5
    extra_hosts:
        - "example.org:172.18.0.3"
        - "example1.org:172.18.0.4"
        
  tft-database:
    image: tft-jena-fuseki:latest
    hostname:  tft-database
    container_name: instance.tft-database
    privileged: true
    networks:
      tft:
        ipv4_address: 172.18.0.6
        
networks:
  tft:
    ipam:
      config:
        - subnet: 172.18.0.0/16
