name: Build

#on: push
on: workflow_dispatch
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image docker
        run: >-
            docker build -t tft-jena-fuseki .

